-- 022_categories_expanded.sql — expanded taxonomy with subcategories

INSERT INTO public.categories (slug, label, sort_order, parent_slug) VALUES
  ('food-beverage', 'Food & Beverage', 1, NULL),
  ('fresh-produce-and-groceries', 'Fresh Produce & Groceries', 101, 'food-beverage'),
  ('packaged-foods-and-snacks', 'Packaged Foods & Snacks', 102, 'food-beverage'),
  ('beverages-and-drinks', 'Beverages & Drinks', 103, 'food-beverage'),
  ('bakery-and-confectionery', 'Bakery & Confectionery', 104, 'food-beverage'),
  ('spices-sauces-and-condiments', 'Spices, Sauces & Condiments', 105, 'food-beverage'),
  ('organic-and-health-foods', 'Organic & Health Foods', 106, 'food-beverage'),
  ('catering-and-ready-meals', 'Catering & Ready Meals', 107, 'food-beverage'),
  ('baby-and-toddler-food', 'Baby & Toddler Food', 108, 'food-beverage'),
  ('coffee-tea-and-hot-drinks', 'Coffee, Tea & Hot Drinks', 109, 'food-beverage'),
  ('fashion', 'Fashion', 2, NULL),
  ('men-s-clothing', 'Men''s Clothing', 201, 'fashion'),
  ('women-s-clothing', 'Women''s Clothing', 202, 'fashion'),
  ('children-s-clothing', 'Children''s Clothing', 203, 'fashion'),
  ('shoes-and-footwear', 'Shoes & Footwear', 204, 'fashion'),
  ('bags-and-luggage', 'Bags & Luggage', 205, 'fashion'),
  ('accessories', 'Accessories', 206, 'fashion'),
  ('traditional-and-cultural-wear', 'Traditional & Cultural Wear', 207, 'fashion'),
  ('work-and-uniform-wear', 'Work & Uniform Wear', 208, 'fashion'),
  ('underwear-and-sleepwear', 'Underwear & Sleepwear', 209, 'fashion'),
  ('watches-fashion', 'Watches (Fashion)', 210, 'fashion'),
  ('sunglasses-and-eyewear', 'Sunglasses & Eyewear', 211, 'fashion'),
  ('electronics', 'Electronics', 3, NULL),
  ('mobile-phones-and-tablets', 'Mobile Phones & Tablets', 301, 'electronics'),
  ('phone-and-tablet-accessories', 'Phone & Tablet Accessories', 302, 'electronics'),
  ('computers-and-laptops', 'Computers & Laptops', 303, 'electronics'),
  ('computer-accessories', 'Computer Accessories', 304, 'electronics'),
  ('tvs-and-home-entertainment', 'TVs & Home Entertainment', 305, 'electronics'),
  ('audio-and-headphones', 'Audio & Headphones', 306, 'electronics'),
  ('cameras-and-photography', 'Cameras & Photography', 307, 'electronics'),
  ('gaming-consoles-and-accessories', 'Gaming Consoles & Accessories', 308, 'electronics'),
  ('smart-home-and-iot-devices', 'Smart Home & IoT Devices', 309, 'electronics'),
  ('wearable-technology', 'Wearable Technology', 310, 'electronics'),
  ('cables-chargers-and-power-banks', 'Cables, Chargers & Power Banks', 311, 'electronics'),
  ('solar-and-power-equipment', 'Solar & Power Equipment', 312, 'electronics'),
  ('electronic-components-and-parts', 'Electronic Components & Parts', 313, 'electronics'),
  ('beauty', 'Beauty', 4, NULL),
  ('skincare', 'Skincare', 401, 'beauty'),
  ('makeup-and-cosmetics', 'Makeup & Cosmetics', 402, 'beauty'),
  ('hair-care-and-styling', 'Hair Care & Styling', 403, 'beauty'),
  ('fragrances-and-perfumes', 'Fragrances & Perfumes', 404, 'beauty'),
  ('nail-care', 'Nail Care', 405, 'beauty'),
  ('men-s-grooming', 'Men''s Grooming', 406, 'beauty'),
  ('beauty-tools-and-accessories', 'Beauty Tools & Accessories', 407, 'beauty'),
  ('salon-and-spa-products', 'Salon & Spa Products', 408, 'beauty'),
  ('bath-and-body', 'Bath & Body', 409, 'beauty'),
  ('home-living', 'Home & Living', 5, NULL),
  ('furniture', 'Furniture', 501, 'home-living'),
  ('home-decor', 'Home Decor', 502, 'home-living'),
  ('kitchen-and-dining', 'Kitchen & Dining', 503, 'home-living'),
  ('bedding-and-linens', 'Bedding & Linens', 504, 'home-living'),
  ('bathroom-essentials', 'Bathroom Essentials', 505, 'home-living'),
  ('cleaning-and-household-supplies', 'Cleaning & Household Supplies', 506, 'home-living'),
  ('lighting-and-lamps', 'Lighting & Lamps', 507, 'home-living'),
  ('storage-and-organization', 'Storage & Organization', 508, 'home-living'),
  ('garden-and-outdoor-living', 'Garden & Outdoor Living', 509, 'home-living'),
  ('home-appliances', 'Home Appliances', 510, 'home-living'),
  ('cookware-and-bakeware', 'Cookware & Bakeware', 511, 'home-living'),
  ('curtains-rugs-and-textiles', 'Curtains, Rugs & Textiles', 512, 'home-living'),
  ('services', 'Services', 6, NULL),
  ('repair-and-maintenance', 'Repair & Maintenance', 601, 'services'),
  ('cleaning-services', 'Cleaning Services', 602, 'services'),
  ('delivery-and-logistics', 'Delivery & Logistics', 603, 'services'),
  ('professional-and-consulting', 'Professional & Consulting', 604, 'services'),
  ('beauty-and-personal-care-services', 'Beauty & Personal Care Services', 605, 'services'),
  ('education-and-tutoring', 'Education & Tutoring', 606, 'services'),
  ('tech-and-it-services', 'Tech & IT Services', 607, 'services'),
  ('events-and-entertainment', 'Events & Entertainment', 608, 'services'),
  ('photography-and-videography', 'Photography & Videography', 609, 'services'),
  ('legal-and-financial-services', 'Legal & Financial Services', 610, 'services'),
  ('home-improvement-services', 'Home Improvement Services', 611, 'services'),
  ('health-and-wellness-services', 'Health & Wellness Services', 612, 'services'),
  ('agriculture', 'Agriculture', 7, NULL),
  ('seeds-and-plants', 'Seeds & Plants', 701, 'agriculture'),
  ('fertilizers-and-pesticides', 'Fertilizers & Pesticides', 702, 'agriculture'),
  ('farm-tools-and-equipment', 'Farm Tools & Equipment', 703, 'agriculture'),
  ('livestock-and-poultry', 'Livestock & Poultry', 704, 'agriculture'),
  ('fresh-farm-produce', 'Fresh Farm Produce', 705, 'agriculture'),
  ('animal-feed-and-supplements', 'Animal Feed & Supplements', 706, 'agriculture'),
  ('irrigation-and-water-systems', 'Irrigation & Water Systems', 707, 'agriculture'),
  ('greenhouse-and-nursery-supplies', 'Greenhouse & Nursery Supplies', 708, 'agriculture'),
  ('harvesting-and-processing', 'Harvesting & Processing', 709, 'agriculture'),
  ('health-wellness', 'Health & Wellness', 8, NULL),
  ('vitamins-and-supplements', 'Vitamins & Supplements', 801, 'health-wellness'),
  ('medical-supplies-and-equipment', 'Medical Supplies & Equipment', 802, 'health-wellness'),
  ('first-aid-and-safety', 'First Aid & Safety', 803, 'health-wellness'),
  ('personal-care-and-hygiene', 'Personal Care & Hygiene', 804, 'health-wellness'),
  ('fitness-and-nutrition', 'Fitness & Nutrition', 805, 'health-wellness'),
  ('herbal-and-natural-remedies', 'Herbal & Natural Remedies', 806, 'health-wellness'),
  ('mobility-and-disability-aids', 'Mobility & Disability Aids', 807, 'health-wellness'),
  ('maternity-and-nursing-care', 'Maternity & Nursing Care', 808, 'health-wellness'),
  ('sexual-wellness', 'Sexual Wellness', 809, 'health-wellness'),
  ('sports-outdoors', 'Sports & Outdoors', 9, NULL),
  ('exercise-and-fitness-equipment', 'Exercise & Fitness Equipment', 901, 'sports-outdoors'),
  ('team-sports', 'Team Sports', 902, 'sports-outdoors'),
  ('outdoor-and-camping-gear', 'Outdoor & Camping Gear', 903, 'sports-outdoors'),
  ('cycling', 'Cycling', 904, 'sports-outdoors'),
  ('water-sports', 'Water Sports', 905, 'sports-outdoors'),
  ('athletics-and-running', 'Athletics & Running', 906, 'sports-outdoors'),
  ('sportswear-and-activewear', 'Sportswear & Activewear', 907, 'sports-outdoors'),
  ('hunting-and-fishing', 'Hunting & Fishing', 908, 'sports-outdoors'),
  ('yoga-and-pilates', 'Yoga & Pilates', 909, 'sports-outdoors'),
  ('automotive', 'Automotive', 10, NULL),
  ('car-parts-and-accessories', 'Car Parts & Accessories', 1001, 'automotive'),
  ('motorcycles-and-boda-boda', 'Motorcycles & Boda Boda', 1002, 'automotive'),
  ('tires-and-wheels', 'Tires & Wheels', 1003, 'automotive'),
  ('car-electronics-and-gps', 'Car Electronics & GPS', 1004, 'automotive'),
  ('oils-fluids-and-lubricants', 'Oils, Fluids & Lubricants', 1005, 'automotive'),
  ('tools-and-garage-equipment', 'Tools & Garage Equipment', 1006, 'automotive'),
  ('car-care-and-cleaning', 'Car Care & Cleaning', 1007, 'automotive'),
  ('bicycles-and-scooters', 'Bicycles & Scooters', 1008, 'automotive'),
  ('vehicle-batteries', 'Vehicle Batteries', 1009, 'automotive'),
  ('books-stationery', 'Books & Stationery', 11, NULL),
  ('books-and-literature', 'Books & Literature', 1101, 'books-stationery'),
  ('school-supplies', 'School Supplies', 1102, 'books-stationery'),
  ('office-supplies', 'Office Supplies', 1103, 'books-stationery'),
  ('art-and-craft-supplies', 'Art & Craft Supplies', 1104, 'books-stationery'),
  ('writing-instruments', 'Writing Instruments', 1105, 'books-stationery'),
  ('notebooks-and-paper', 'Notebooks & Paper', 1106, 'books-stationery'),
  ('educational-materials', 'Educational Materials', 1107, 'books-stationery'),
  ('magazines-and-media', 'Magazines & Media', 1108, 'books-stationery'),
  ('calendars-and-planners', 'Calendars & Planners', 1109, 'books-stationery'),
  ('kids-baby', 'Kids & Baby', 12, NULL),
  ('baby-clothing', 'Baby Clothing', 1201, 'kids-baby'),
  ('kids-clothing', 'Kids Clothing', 1202, 'kids-baby'),
  ('diapering-and-bathing', 'Diapering & Bathing', 1203, 'kids-baby'),
  ('baby-gear-and-furniture', 'Baby Gear & Furniture', 1204, 'kids-baby'),
  ('feeding-and-nursing', 'Feeding & Nursing', 1205, 'kids-baby'),
  ('baby-toys-and-activity', 'Baby Toys & Activity', 1206, 'kids-baby'),
  ('strollers-and-car-seats', 'Strollers & Car Seats', 1207, 'kids-baby'),
  ('kids-shoes-and-accessories', 'Kids Shoes & Accessories', 1208, 'kids-baby'),
  ('maternity-products', 'Maternity Products', 1209, 'kids-baby'),
  ('pets', 'Pets', 13, NULL),
  ('dog-supplies', 'Dog Supplies', 1301, 'pets'),
  ('cat-supplies', 'Cat Supplies', 1302, 'pets'),
  ('bird-supplies', 'Bird Supplies', 1303, 'pets'),
  ('fish-and-aquarium', 'Fish & Aquarium', 1304, 'pets'),
  ('pet-food-and-treats', 'Pet Food & Treats', 1305, 'pets'),
  ('pet-grooming', 'Pet Grooming', 1306, 'pets'),
  ('pet-toys-and-accessories', 'Pet Toys & Accessories', 1307, 'pets'),
  ('pet-health-and-medicine', 'Pet Health & Medicine', 1308, 'pets'),
  ('small-animal-supplies', 'Small Animal Supplies', 1309, 'pets'),
  ('jewelry-watches', 'Jewelry & Watches', 14, NULL),
  ('necklaces-and-pendants', 'Necklaces & Pendants', 1401, 'jewelry-watches'),
  ('earrings', 'Earrings', 1402, 'jewelry-watches'),
  ('rings', 'Rings', 1403, 'jewelry-watches'),
  ('bracelets-and-bangles', 'Bracelets & Bangles', 1404, 'jewelry-watches'),
  ('watches', 'Watches', 1405, 'jewelry-watches'),
  ('traditional-and-cultural-jewelry', 'Traditional & Cultural Jewelry', 1406, 'jewelry-watches'),
  ('fine-jewelry', 'Fine Jewelry', 1407, 'jewelry-watches'),
  ('fashion-jewelry', 'Fashion Jewelry', 1408, 'jewelry-watches'),
  ('jewelry-making-supplies', 'Jewelry Making Supplies', 1409, 'jewelry-watches'),
  ('toys-games', 'Toys & Games', 15, NULL),
  ('action-figures-and-dolls', 'Action Figures & Dolls', 1501, 'toys-games'),
  ('board-games-and-puzzles', 'Board Games & Puzzles', 1502, 'toys-games'),
  ('educational-toys', 'Educational Toys', 1503, 'toys-games'),
  ('outdoor-play-equipment', 'Outdoor Play Equipment', 1504, 'toys-games'),
  ('remote-control-and-electronic-toys', 'Remote Control & Electronic Toys', 1505, 'toys-games'),
  ('building-and-construction-toys', 'Building & Construction Toys', 1506, 'toys-games'),
  ('arts-and-craft-kits', 'Arts & Craft Kits', 1507, 'toys-games'),
  ('party-games-and-supplies', 'Party Games & Supplies', 1508, 'toys-games'),
  ('collectibles', 'Collectibles', 1509, 'toys-games'),
  ('arts-crafts', 'Arts & Crafts', 16, NULL),
  ('painting-and-drawing', 'Painting & Drawing', 1601, 'arts-crafts'),
  ('sewing-and-knitting', 'Sewing & Knitting', 1602, 'arts-crafts'),
  ('handmade-and-artisan-goods', 'Handmade & Artisan Goods', 1603, 'arts-crafts'),
  ('craft-materials-and-supplies', 'Craft Materials & Supplies', 1604, 'arts-crafts'),
  ('scrapbooking-and-paper-crafts', 'Scrapbooking & Paper Crafts', 1605, 'arts-crafts'),
  ('beading-and-jewelry-making', 'Beading & Jewelry Making', 1606, 'arts-crafts'),
  ('woodworking-and-carpentry-crafts', 'Woodworking & Carpentry Crafts', 1607, 'arts-crafts'),
  ('musical-instruments-handmade', 'Musical Instruments (Handmade)', 1608, 'arts-crafts'),
  ('custom-and-personalized-gifts', 'Custom & Personalized Gifts', 1609, 'arts-crafts'),
  ('building-hardware', 'Building & Hardware', 17, NULL),
  ('building-materials', 'Building Materials', 1701, 'building-hardware'),
  ('plumbing-supplies', 'Plumbing Supplies', 1702, 'building-hardware'),
  ('electrical-supplies', 'Electrical Supplies', 1703, 'building-hardware'),
  ('paint-and-finishes', 'Paint & Finishes', 1704, 'building-hardware'),
  ('tools-and-power-tools', 'Tools & Power Tools', 1705, 'building-hardware'),
  ('doors-windows-and-locks', 'Doors, Windows & Locks', 1706, 'building-hardware'),
  ('roofing-and-insulation', 'Roofing & Insulation', 1707, 'building-hardware'),
  ('tiles-and-flooring', 'Tiles & Flooring', 1708, 'building-hardware'),
  ('safety-equipment-and-ppe', 'Safety Equipment & PPE', 1709, 'building-hardware'),
  ('garden-tools-and-equipment', 'Garden Tools & Equipment', 1710, 'building-hardware'),
  ('other', 'Other', 18, NULL),
  ('general-merchandise', 'General Merchandise', 1801, 'other'),
  ('vintage-and-antiques', 'Vintage & Antiques', 1802, 'other'),
  ('wholesale-and-bulk', 'Wholesale & Bulk', 1803, 'other'),
  ('uncategorized', 'Uncategorized', 1804, 'other')
ON CONFLICT (slug) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  parent_slug = EXCLUDED.parent_slug;