"""Stage: image metadata / provenance inspection.

Runs after phash (which already downloaded the image bytes) and before the
expensive Gemini calls. Reads EXIF, XMP and PNG text chunks with Pillow —
no extra dependencies — and rejects images that look like:

* photos with a foreign watermark, URL or brand in EXIF `Copyright` /
  `Artist` / `ImageDescription` / `UserComment`;
* images generated by AI tools (DALL-E, Midjourney, Stable Diffusion,
  Adobe Firefly, …) advertised in EXIF `Software` or PNG `parameters`
  chunks;
* stock / marketplace exports whose XMP `xmpRights:WebStatement` points
  at another site (Shutterstock, Alibaba, Jumia, Amazon, eBay, …).

The rule is deliberately strict: if the image says "I came from somewhere
that isn't Midora", we tell the merchant to upload their own photo.
"""
from __future__ import annotations

import logging
import re
from typing import Iterable, Optional

logger = logging.getLogger(__name__)

# EXIF tag numbers we care about. Kept as ints so we don't have to import
# Pillow's TAGS table (which pulls in extra data at import time).
_EXIF_TAGS = {
    270: "ImageDescription",
    305: "Software",
    315: "Artist",
    316: "HostComputer",
    33432: "Copyright",
    37510: "UserComment",
    # Windows XP tags — often UTF-16-LE encoded.
    40091: "XPTitle",
    40092: "XPComment",
    40093: "XPAuthor",
    40094: "XPKeywords",
    40095: "XPSubject",
}

# Any URL / domain hit (except our own) rejects the image.
_URL_RE = re.compile(
    r"(?:https?://|www\.)[^\s\"'<>]+|[a-z0-9][a-z0-9\-]*\.(?:com|co|net|io|org|shop|store|africa|ug|ke|tz|rw)\b",
    re.IGNORECASE,
)

# Substrings the merchant is allowed to keep in metadata (our own tooling).
_ALLOWED_DOMAIN_HINTS = ("midora", "midoraonline")

# Software / tool names that indicate AI-generated or stock-sourced images.
# We do NOT reject on pure camera/editor names (Photoshop, Lightroom, Snapseed,
# iPhone, Android, GIMP, …) — those are perfectly fine on a real photo.
_BANNED_SOFTWARE_KEYWORDS = (
    "dall-e",
    "dalle",
    "midjourney",
    "stable diffusion",
    "sd-webui",
    "automatic1111",
    "comfyui",
    "adobe firefly",
    "leonardo.ai",
    "runway",
    "imagen",
    "gemini image",
    "grok image",
    "flux.1",
    "flux1",
    "shutterstock",
    "istock",
    "getty",
    "adobe stock",
    "pexels",
    "unsplash",
    "pixabay",
    "alibaba",
    "aliexpress",
    "amazon",
    "ebay",
    "jumia",
    "kilimall",
    "temu",
)

# XMP tags that commonly leak provenance URLs.
_XMP_URL_TAGS_RE = re.compile(
    r"<(?:xmpRights:WebStatement|dc:source|photoshop:Source|Iptc4xmpCore:CreatorContactInfo)[^>]*>([^<]+)</",
    re.IGNORECASE,
)


def _decode_xp_bytes(value: bytes) -> str:
    # Windows XP EXIF tags are UTF-16-LE with a trailing NUL; strip both.
    try:
        return value.decode("utf-16-le", errors="ignore").rstrip("\x00").strip()
    except Exception:
        return ""


def _stringify(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        # XPTitle etc. are the common byte-valued tags. Try UTF-16 first,
        # fall back to UTF-8/latin-1 so we don't lose visible URL text.
        text = _decode_xp_bytes(value)
        if text:
            return text
        for enc in ("utf-8", "latin-1"):
            try:
                return value.decode(enc, errors="ignore").strip()
            except Exception:
                continue
        return ""
    return str(value).strip()


def _contains_foreign_url(text: str) -> Optional[str]:
    if not text:
        return None
    matches = _URL_RE.findall(text)
    for m in matches:
        lowered = m.lower()
        if any(allowed in lowered for allowed in _ALLOWED_DOMAIN_HINTS):
            continue
        return m
    return None


def _contains_banned_software(text: str) -> Optional[str]:
    if not text:
        return None
    lowered = text.lower()
    for kw in _BANNED_SOFTWARE_KEYWORDS:
        if kw in lowered:
            return kw
    return None


def _collect_exif_strings(image) -> Iterable[tuple[str, str]]:
    try:
        exif = image.getexif()
    except Exception as exc:
        logger.debug("metadata: getexif failed: %s", exc)
        return []
    out: list[tuple[str, str]] = []
    for tag_id, name in _EXIF_TAGS.items():
        try:
            raw = exif.get(tag_id)
        except Exception:
            continue
        if raw is None:
            continue
        text = _stringify(raw)
        if text:
            out.append((name, text))
    return out


def _collect_xmp_strings(image) -> Iterable[tuple[str, str]]:
    xmp_raw = image.info.get("xmp") if hasattr(image, "info") else None
    if not xmp_raw:
        return []
    xmp_text = _stringify(xmp_raw)
    if not xmp_text:
        return []
    out: list[tuple[str, str]] = [("XMP", xmp_text)]
    # Pull out common URL-bearing tags explicitly for cleaner rejection reasons.
    for match in _XMP_URL_TAGS_RE.finditer(xmp_text):
        out.append(("XMP:tag", match.group(1).strip()))
    return out


def _collect_png_text(image) -> Iterable[tuple[str, str]]:
    if not hasattr(image, "info"):
        return []
    # These are the chunks Stable Diffusion / ComfyUI / A1111 write.
    keys = (
        "parameters",
        "prompt",
        "workflow",
        "Comment",
        "Description",
        "Software",
        "Source",
        "Copyright",
        "Author",
        "sd-metadata",
    )
    out: list[tuple[str, str]] = []
    for k in keys:
        v = image.info.get(k)
        if not v:
            continue
        text = _stringify(v)
        if text:
            out.append((f"png:{k}", text))
    return out


def check(image_bytes: bytes, url: str = "") -> Optional[str]:
    """Return a rejection reason string, or None when the metadata is clean.

    Called once per image after the phash download step. `image_bytes` may
    be None if the download failed earlier — the caller skips this stage
    in that case.
    """
    if not image_bytes:
        return None

    try:
        from PIL import Image
    except ImportError:  # pragma: no cover - Pillow is a hard dependency
        logger.error("Pillow not installed; skipping metadata stage")
        return None

    import io

    try:
        with Image.open(io.BytesIO(image_bytes)) as image:
            image.load()
            fields: list[tuple[str, str]] = []
            fields.extend(_collect_exif_strings(image))
            fields.extend(_collect_xmp_strings(image))
            fields.extend(_collect_png_text(image))
    except Exception as exc:
        logger.debug("metadata: unable to open image %s: %s", url, exc)
        return None

    for name, text in fields:
        banned = _contains_banned_software(text)
        if banned:
            return (
                "image metadata mentions "
                f"'{banned}' — please upload your own photo taken with your phone or camera"
            )
    for name, text in fields:
        foreign = _contains_foreign_url(text)
        if foreign:
            return (
                f"image metadata contains a non-Midora URL/watermark ({foreign[:60]}) — "
                "please upload your own photo"
            )

    return None
